function [fitresult, gof] = createFit1(tt, m)
%CREATEFIT1(TT,M)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: tt
%      Y Output: m
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Dec-2024 18:19:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tt, m );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [6.8124359596814e-41 0.0460946096619759];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% 
% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'm vs. tt', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'tt', 'Interpreter', 'none' );
% ylabel( 'm', 'Interpreter', 'none' );
% grid on
% 
% 
